"""
File: hangman.py
Name: Ray
-----------------------------
This program plays hangman game.
Users see a dashed word, trying to
correctly figure the un-dashed word out
by inputting one character each round.
If the user input is correct, show the
updated word on console. Players have N_TURNS
chances to try and win this game.
"""


import random


# This constant controls the number of guess the player has.
N_TURNS = 7


def main():
    """
    This program uses guess, a string variable consists of characters and dashes. The program completes when either
    a) all characters in the word generated by the function random_word are un-dashed after the user inputs a character
    or b) the user has failed to input the character contained in the word for N_TURNS times.
    """
    ans = random_word()
    rev_guess = ans
    # rev_guess stores the value of the reverse of the variable guess.
    # When the character of guess is dashed, the corresponding character of rev_guess is the character in ans.
    dashed = ''
    for i in range(len(ans)):
        dashed += '-'
    guess = dashed
    n = N_TURNS

    while True:
        print('The word looks like: ' + guess)
        print('You have ' + str(n) + ' wrong guesses left.')
        input_ch = input('Your guess: ').upper()
        while not str.isalpha(input_ch) or len(input_ch) != 1:
            print('Illegal format')
            input_ch = input('Your guess: ').upper()
        while input_ch in rev_guess:
            rev_guess = rev_guess[:rev_guess.find(input_ch)] + '-' + rev_guess[rev_guess.find(input_ch)+1:]
        for i in range(len(rev_guess)):
            if rev_guess[i] == '-':
                guess = guess[:i] + ans[i] + guess[i+1:]
        if input_ch in ans:
            if guess != ans:
                print('You are correct!')
            else:
                print('You are correct!')
                print('You win!!')
                print('The answer is: ' + ans)
                break
        else:
            if input_ch not in ans:
                if n != 1:
                    print('There is no ' + input_ch + "'s" + ' in the word.')
                    n -= 1
                else:
                    print('There is no ' + input_ch + "'s" + ' in the word.')
                    print('You are completely hung :(')
                    print('The answer is: ' + ans)
                    break


def random_word():
    num = random.choice(range(9))
    if num == 0:
        return "NOTORIOUS"
    elif num == 1:
        return "GLAMOROUS"
    elif num == 2:
        return "CAUTIOUS"
    elif num == 3:
        return "DEMOCRACY"
    elif num == 4:
        return "BOYCOTT"
    elif num == 5:
        return "ENTHUSIASTIC"
    elif num == 6:
        return "HOSPITALITY"
    elif num == 7:
        return "BUNDLE"
    elif num == 8:
        return "REFUND"


# DO NOT EDIT CODE BELOW THIS LINE #

if __name__ == '__main__':
    main()
